<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;

class BlogsTableSeeder extends Seeder
{
    protected $blogs = [
        [
            'category_id'   => 1,
            'title'         => '5 poharas oldat',
            'editor'        => 'Dr.Nagy Bea',
            'images_path'   => '/images/blogs/5-poharas-oldat.jpg',
            'description'   => 'Hozzávalók:<br> 2 golyó homeopátiás szer, 5 pohárban víz, 1 (műanyag) kanál <br><br> az első pohárban teljesen feloldjuk a 2 golyót a műanyag kanállal 10x megkeverjük függőlegesen (!) kiemeljük a kanalat, amelyre tapad kb. 1 csöpp oldat <br><br> a második pohár vizet megkeverjük vele 10x függőlegesen (!) kiemeljük a kanalat, amelyre tapad kb. 1 csöpp oldat <br><br> a harmadik pohár vizet megkeverjük vele 10x függőlegesen (!) kiemeljük a kanalat, amelyre tapad kb. 1 csöpp oldat <br><br> a negyedik pohár vizet megkeverjük vele 10x függőlegesen (!) kiemeljük a kanalat, amelyre tapad kb. 1 csöpp oldat <br><br> az ötödik pohár vizet megkeverjük vele 10x az ötödik pohárból iszunk 1 kortyot <br><br> <strong>FONTOS! A homeopátiás szer és oldat ne érintkezzen fémmel (műanyag kanál)</strong> ',
        ],
        [
            'category_id'   => 1,
            'title'         => 'Allergia vagy nátha?',
            'editor'        => 'Dr.Nagy Bea',
            'images_path'   => '/images/blogs/allergia-vagy-natha.png',
            'description'   => '<p>A nátha inkább ősztől tavaszig, míg a szénanátha inkább nyáron mutatkozik. Akinek nyáron van elhúzódó náthája, az már utalhat allergiára. Kifejezett orrduzzanattal kezdődő, majd váladékozzással járó , de két hét alatt lecsendesedő tüneteket a nátha okoz. A szénanátha nem gyógyul meg egy hónapig sem. A gyakori hurutos, náthás tünetek 85%-át vírusok okozzák. Ezekre nem hat az antibiotikum. Ezért lázas betegség esetén nem feltétlenül kell antibiotikumot kapnia a gyermeknek, a láz enyhítése, sok folyadék, vitamin adása szükséges. Az immunrendszer felkészül a betegségek kivédésére és ez az allergia kialakulása ellen hat.</p> <p>Az allergiás nátha tünetei: tüsszögés,vízszerű orrfolyás, orrdugulás.Társulhat szem viszketéssel, könnyezéssel. Az allergia egyik legfőbb tünete, hogy általában mindig ugyanazt a szervet érinti. Ezért ha valakinek orrdugulása van vagy folyik az orra, illetve viszket a szeme, garatja, füle, akkor az illetőnek szénanáthája lehet. Ha a panaszok egész évben fennállnak akkor a közvetlen környezetünkben,lakásunkban van vagy lehet az ok.</p> <p>Az allergiát az immunrendszer túlműködése okozza, egyes esetekben a szervezet, az egyébként ártalmatlan környezeti faktorokra (pollen, penész) heves reakcióval válaszol. Ilyenkor a szervezet hisztamin felszabadításával próbál meg védekezni, ennek következménye pedig a nyálkahártyák megduzzadása, orrfolyás, köhögés, tüsszögés. Az allergia nem fertőző, de egyes esetekben az allergiára való hajlam örökölhető.</p> <p>Az allergiás tünetek kor szerint megoszlanak. Csecsemőkorban főleg az ételallergia okoz problémát, elsősorban a tejallergia, ami bőr-  emésztési- és légúti tünetekben nyilvánulhat meg. Ha ismert a család allergiára való hajlama, fontos a gyermeket sokáig szoptatni, és ha szükséges, tehéntej helyett hypoallergén, vagy teljesen tejmentes tápszerrel táplálni. A légúti allergiák 2-3 éves korban jelennek meg, leggyakoribb a háziporatka, az állati szőr, a toll és a penészgomba allergia. Ilyenkor köhögés, fulladás jelentkezik, főleg az éjszakai és hajnali órákban. 6-7 éves korban jellemző a szénanátha, a kötőhártya gyulladás, amelyekért a pollenek tehetők felelőssé. Az utóbbi időben az allergia megjelenése sajnos egyre fiatalabb korra tehető.</p><p>Gyógyszeres kezelés: antihisztamin tartalmú gyógyszerek  illetve a helyi allergiás tünetekre orrspray, szemcsepp is alkalmazható. Az antihisztaminok néha álmosságot okozhatnak.
            Fontos a megelőzés, hiszen ha meg tudunk előzni egy allergiás reakciót, nem kell gyógyszert használnunk. Bizonyos allergéneket ki lehet küszöbölni az életünkből. Ilyenek például az állati szőrök, melyek ha súlyos allergiát okoznak, el lehet az állatokat távolítani a gyerek mellől, illetve ételallergia esetén az allergént tartalmazó étel kihagyása az étrendből. Mivel a házipor az egyik leggyakoribb allergén, a lakást pormentessé kell tenni, amennyire csak lehetséges. Kerülni kell a háziállatokat és a padlót naponta fel kell mosni. Hordjunk maszkot söpréskor és az ágynemű cseréjekor. A pollenek által kiváltott szénanátha ellen nehéz védekezni. Kerülni kell a pollennel való érintkezést, zárva kell tartani az ablakokat.</p> <p>A pollenallergiás gyermek ne töltsön hosszabb időt a szabadban a virágzás idején. A szabadban való sportolás, futás fokozhatja a tüneteket. A lakásban a szellőztetés, pollenszűrőn keresztül ajánlott. Utazáskor a kocsiban használjanak pollenszűrőt, zárt ablakkal közlekedjenek. Szabadban való tartózkodás után érdemes hajat  mosni. A hajba került virág - porszemeket a gyermek éjszaka belélegezheti, s ezek tüneteket válthatnak ki. A nyaralást olyan helyre tervezzék, ahol nem találhatók az adott pollenek: tengerpart, hegyvidék.A pollenallergiások kezdjék el időben szedni  gyógyszereiket, hogy súlyosabb tünetek ne alakuljanak ki és ne jelentkezzenek a késői gyulladásos elváltozások. Ismerni kell a keresztallergiákat is, pl. parlagfű allergiásoknál keresztallergiát okozhat a görögdinnye, így nem tanácsos fogyasztása, mert ugyanolyan allergiás tüneteket tud okozni, mint a parlagfű. </p>'
        ],
        [
            'category_id'   => 1,
            'title'         => 'A nátha homeopátiás kezelése',
            'editor'        => 'Dr.Nagy Bea',
            'images_path'   => '/images/blogs/a-natha-homeopatias-kezelese.png',
            'description'   => '<p>A nátha banális megbetegedés, ám sok család számára pokollá teszi a téli szezont. Sok esetben, ha belépünk egy óvodába, a gyerekek orra között csak annyi különbség van, hogy kinek milyen színű és állagú váladék csordogál belőle. Egy régi francia közmondás szerint a nátha az orrban kezdődik, és a tüdőben fejeződik be, persze közben útba ejtheti a fület, a melléküregeket és az orrmandulát is.</p> <strong>Miben segíthet a homeopátiás kezelés?</strong><ol><li>Homeopátiával fokozhatjuk a szervezet ellenálló képességét, hogy minél kevésbé legyen fogékony a pathogén kórokozókra.</li><li>Egy jól kiválasztott homeopátiás szerrel lényegesen lerövidíthetjük a betegség időtartamát.</li><li>Nem utolsó sorban klinikai megfigyelések szerint csökken annak az esélye, hogy a fent leírtakhoz hasonlóan a kórokozó a vándorútra induljon – azaz csökkenthető a szövődményes esetek száma.</li><li>Csökkenthető az antibiotikum használat.</li></ol><strong>Az immunrendszer erősítése homeopátiával</strong><p>Ha valaki túl sokat betegeskedik, akkor homeopátiás szempontból a legoptimálisabb, ha meghatározásra kerül az illető alkati szere. Ez annyit jelent, hogy egy 1-1,5 órás beszélgetés során megkeresik az illető hagymaszerű tüneteit, vagyis azt deríti fel a homeopata, hogy miben más ő, mint a többi ember, milyen speciális tünetei vannak mind mentális, mind fizikális tünetek vonatkozásában. Ilyenkor tehát nemcsak az aktuális betegség kerül kikérdezésre, hanem minden, ami a beteggel kapcsolatos. Ezt követően kerülhet sor a homeopátiás gyógyszer kiválasztásra, mely az összes tünetet lefedi.Ha azonban erre nincs lehetőség, vagy idő, akkor számos séma ismert. Az alábbi protokoll pl. egész téli szezonban alkalmazható: Az egyik héten napi 2×5 golyó Echinacea D4 (fitoterápiában is közismert kasvirág homeopátiás formája), a másik héten napi 2×1 tabletta Engystol adandó. Az Engystolt és Echinaceát heti váltásban alkalmazva akár egész téli szezonban alkalmazhatjuk.
Kisgyermekkorban a visszatérő infekciók hátterében, illetve következményeként az orrmandula megnagyobbodása is állhat. Ha adenoid vegetációra utaló tüneteket észlelünk (pl. nyitott szájjal alvás, horkolás, adenoidos szájon át légzés) Lympomyosot cseppet érdemes alkalmaznunk (3×15 csepp adása javasolt 2-3 hónapon keresztül). Klinikai vizsgálatok szerint az esetek 70-80%-ában Lymphomyosot cseppeket alkalmazva az orrmandulák regenerációja figyelhető meg. Mivel a cseppek gyermekeknek könnyebben beadhatóak, ha vagy kockacukorra cseppentjük, vagy vízben oldva adjuk be.</p><strong>Homeopátiás gyógyszerek a nátha kezelésében</strong><p>Hogy megtaláljuk a similét – a „beteg hagymáját” az adott náthára, ahhoz meg kell tudnunk, hogy miképpen náthás, azaz részletesen ki kell kérdeznünk betegségével kapcsolatosan. Hagyományos orvoslásban eszünkbe sem jutna olyan kérdéseket feltenni, csiklandoz-e az orra, vagy inkább feszülést érez, vagy hogy a nap melyik szakaszában csökkennek, vagy fokozódnak a tünetei. Monokomponensű homeopátiás gyógyszer kiválasztásánál azonban a részletek tisztázása nélkül a legtöbb esetben nem boldogulunk. Tehát ami korábban szószátyárságnak tűnt, az most értékes tünetté válhat számunkra, sőt kifejezetten fontos megkérni a betegeket, hogy alaposan figyeljék meg tüneteiket.</p><strong>Milyen kérdéseket érdemes tisztázni?</strong><p>Van-e valami kiváltó ok? Tudja-e valamihez kötni a páciens a betegséget? – pl. huzat, hideg szél, a ruha átnedvesedése. Tünetek helye: pl. ha fáj, akkor hol? Tünetek jellege, érzések: váladék színe, állaga, irritál-e a váladék, esetlegesen szaga, könnyen kifújható-e, mutat-e napszaki ingadozást?</p><strong>Milyen érzetet kelt?</strong><p>Dugul, szárazságérzet, hátracsorgás, fájdalom (ha ez utóbbi fennáll, kérdezzünk rá a fájdalom jellegére is). Modalitások (különböző tényezők hogy befolyásolják) időben (pl. napszak) hőmérséklet (pl. hideg szobában jobb) testhelyzet (pl. fekve dugul az orr) tartózkodási hely (pl. szabad levegőn jobb) Kísérő tünet (pl. rohamokban jelentkező tüsszögés, orrvérzés, szaglás elvesztése, rekedtség, szédülés, gyengeség)</p><strong>A nátha szereinek orrváladék jellege szerinti csoportosítása</strong><p>Lehet, hogy ez esetben kicsit egyszerűsített a fogalmazásmód, de talán könnyebben megjegyezhetővé válnak a homeopátiás gyógyszerek, ha <ol><li>vizes</li><li>mucosus fehér-nyúlós</li><li>sárga, sárgászöld színű orrváladék szerint csoportosítjuk őket.</li></ol></p>
<p>Ez a felosztás általánosságban megfelel a nátha időbeli lefolyásának is. Ha úgy gondolja, hogy egyik gyógyszer sem fedi a tüneteket, a váladék állagának, színének megfelelően Schüssler-sót adhat Joli-jokerként. A Schüssler-sók a homeopátia nagy családján belül egy kis családot képviselnek, mely 12 ásványi só homeopátiás formájának felel meg.</p><p><strong>1.Vizes orrfolyás Joli-joker, ha nem talál megfelelő szert – Ferrum phosphoricum D12-es Schüssler-só </strong><br> A nátha tüneteinek jelentkezése után az első két órában negyedóránként javasolt egy tabletta adagolása, majd 3×1 tablettára kell áttérni. Kisgyermekek, csecsemők esetében 1 tablettát kell fél deci vízben feloldani, és a megfelelő gyakoriságban egy teáskanálkányit adagolni.</p><p><strong>Allium cepa</strong>(C12, vagy C15) Naponta 3×5 golyó, mely a tünetek javulásával ritkítható 2×5, majd 1×5 golyóra. Jellemző módon az orrváladék vizes, maró, gyakran elcsöppen az orr. A náthát könnyezés kíséri, a könny azonban nem mar. A tünetek friss levegő hatására javulnak. </p><p><strong>Euphrasia</strong>(C9, vagy C12) (növényi szer) Naponta 3×5 golyó, mely a tünetek javulásával ritkítható 2×5, majd 1×5 golyóra. Az Euphrasia, vagy más néven szemvidítófű gyakorlatilag az Allium cepa ellentéte. Nem maró bőséges orrfolyás, és maró könnyezés jellemzi.</p> <p><strong>Arsenicum album</strong>(C12, Vagy C15) (ásványi szer) Kis mennyiségű, maró, vizes orrfolyás jellemzi, az orr dugulás érzetével. Az orr általában vörös, és forró.  A beteg állapota melegben javul, szomjas, de jellemző módon apró kortyokban iszik. </p> <p><strong>Nux vomica</strong>(C12, vagy C15) ( növényi szer)
Adagolás: naponta 3×5 golyó, mely a tünetek javulásával ritkítható 2×5, majd 1×5 golyóra. A betegséget sok esetben huzatban, légkondicionált helyiségben való tartózkodás előzi meg. Orrdugulás, és csöpögés gyakran válthatja egymást. A váladék nem maró. Gyakran jelentkezhetnek tüsszögési rohamok.</p><p><strong>Dulcamara</strong>(C12, vagy C15) (növényi szer) Adagolás: Naponta 2×5 golyó A nedvesség, hideg, felfázás hatására kialakuló nátha klasszikus szere. Az orr hideg hatására eldugul, melegben inkább csöpög. </p><p><strong>Sambucus nigra</strong>(C12, C15) Adagolás: csecsemőknek naponta 2×1 golyó feloldva A Sambucus nigra kicsit kakukktojásként van jelen az orrfolyós szerek között, ugyanis elsősorban azoknak a csecsemőknek ajánlott, akiknél az anyuka szörtyögő-duguló orrot tapasztal, mely akár a szoptatást is akadályozza, azonban mégsem szívható le váladék. Itt emelném ki, hogy a homeopátiás szerek használata természetesen nem helyettesíti a megfelelő orrtoilettet, azaz az orrszívást, illetve a helyes technikájú orrfújást. </p> <p><strong>Sticta pulmonaria</strong>(C9) (növényi szer) Napi 3×5 golyó szedése javasolt. Szintén kakukktojás, mert nem nagyon jellemző rá az orrváladékozás, viszont orrgyöknél jelentkező erős fájdalom jelentkezik, mely a homlokba is sugározhat. Gyakran kíséri száraz köhögés. Ha az orrváladékozás beindul, szedését abba kell hagyni, és gyógyszert kell váltani.</p><p><strong>2.Mucosus, fehér-nyúlós orrfolyás Joli-jokerként Kalium chloratum D6-os Schüssler-só javasolható </strong>, napi 3×1 tablettás adagolásban. Kisgyermekek, csecsemők esetében 1 tablettát kell fél deci vízben feloldani, és megfelelő gyakoriságban egy teáskanálkányit adagolni.</p> <p><strong>3. Nyákos –gennyes mucopurulens nátha Joli-jokerként, ha nem talál megfelelő szert a Kalium sulfuricum D6-os Schüssler-sót javasolhat, </strong>naponta 3×1 tablettás adagolásban. Kisgyermekek, csecsemők esetében 1 tablettát kell fél deci vízben feloldani, és megfelelő gyakoriságban egy teáskanálkányit adagolni.</p><p><strong>Hepar sulfuris</strong>(C12-C15) (ásványi) Adagolás: 2×5 golyó Bőséges sárgás-gennyes váladékozás jellemzi. A beteg fázós, intoleráns minden külső behatással szemben. A váladék maró, gyakran okoz pörkösödét. Gyakran megfigyelhető a környéki nyirokcsomók duzzanata. </p><p><strong>Hydrastis (C12/C15)</strong>Adagolás: 2×5 golyó
A Hydrastisra sűrű, sárga, maró váladékozás jellemző, mely „reccsenő „hanggal ürül. Egyszerre nagy mennyiségű váladék távozik, mely akár egy egész zsebkendőt is megtölt. A nyelv lepedékes, a száj keserű ízű.</p><p><strong>Kalium bichromicum (C12, vagy C15)</strong>Adagolás: 2×5 golyó Zselészerű,”rágószerűen húzható” nyúlós fehéressárga váladék jellemzi. Az arcüregek felett kifejezett érzékenység jelentkezhet, a beteg nem bír lehajolni a fájdalomtól. A panaszok hidegre, és nyomásra romlanak. </p> <p><strong>Mercurius solubilis</strong>(C12, vagy C15)(ásványi szer) Adagolás: 2x 5 golyó Sárgászöld, maró bő orrfolyás jellemzi. A lehelet bűzös, a nyelv megtekintésekor a lepedékes nyelven fogbenyomatok láthatók. Fokozott nyálképződés, nyálfolyás jelentkezhet. </p><p><strong>Pulsatilla</strong>(C12, vagy C15) Sűrű, ragacsos orrváladék jellemzi. Az orr dugul, átmenetileg a szaglás is elveszik. Panaszai friss levegőn javulnak. A beteg feltűnően nem szomjas. Babusgatás, társaság javít az állapotán. </p><p><strong>A rhinitis helyi kezelése</strong>Fenti szerek mellé, vagy önállóan is alkalmazhatjuk az Euphorbium Comp. Heel orrsprayt. Az Euphorbium az egyedüli orrspray, melynek kimutatott antivirális hatása is van. Plaquereductios vizsgálat szerint az RSV vírustörzsek szaporodását 40%os arányban gátolja, melynek csecsemő, és gyermekkorban lehet különösen fontos szerepe. Mivel az Euphorbium homeopátiás hatóanyagait fiziológiás sóban oldották, így nemcsak a gyulladást csökkenti, hanem a tengeri só oldatokhoz hasonlóan fellazítja a váladékot, és segíti kiürülését. Szemben a hagyományos orrcseppekkel, alkalmazása során nem kell nyálkahártya károsító hatástól tartani, így hosszabb időn keresztül is adható.</p>'
        ],
    ];

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        foreach($this->blogs as $blog) {
            DB::table('blogs')->insert([
                'category_id'   => $blog['category_id'],
                'slug'          => str_slug($blog['title'], '-'),
                'title'         => $blog['title'],
                'editor'        => $blog['editor'],
                'images_path'   => $blog['images_path'],
                'description'   => $blog['description'],
                'created_at'    => Carbon::now()
            ]);
        }
    }
}
